version: "3.9"

##############################################
# Common config
##############################################

x-app-base: &app-base
  image: app_base
  stdin_open: true
  tty: true
  volumes:
    - .:/app

##############################################
# Services
##############################################

services:
  web:
    <<: *app-base
    build: .
    ports:
      - "3001:3001"
    command: ./bin/rails s -p 3001 -b '0.0.0.0'
    depends_on:
      - database
    tty: true
    stdin_open: true
  database:
    image: postgres:latest
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: demo_development
      POSTGRES_HOST_AUTH_METHOD: trust